server:
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: true


spring:
  datasource:
    username: 'pracktika2021'
    password: 'KC8mmymg7vL3'
    url: jdbc:postgresql://practika2021.opencode.su:5454/postgres
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true

