server:
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: true

spring:

  datasource:
    username: 'pracktika2021'
    password: 'KC8mmymg7vL3'
    url: jdbc:postgresql://practika2021.opencode.su:5454/postgres
    driver-class-name: 'org.postgresql.Driver'

  jpa:
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: 'validate'
    show-sql: true
    open-in-view: true

  minio:
    url: https://practika2021.opencode.su:9000/
    bucket: file #Minio Bucket name for app
    access-key: pracktika2021
    secret-key: KC8mmymg7vL3
    secure: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 35541507052-oh08hc1v6alfibvudf2nt6q30119pise.apps.googleusercontent.com
            clientSecret: 3yq3zm1rFH0ALs3t7dfrQtkG



